### ISSUE TITLE
Remove need for Proxy

### ISSUE THREAD

**Issue by ColinRobbins** [GeoffAtHome/lightwave#9]
Hi Geoff,

I've made a PR to remove the need for a proxy in HA.
I have the permissions I need accept the PR, and create the PyPI.
Just want to check you are OK with the update before I do.

Cheers.

**Comment by GeoffAtHome** [comment]
Hi Colin,

 

Happy for you to make the change. If you want to delay, I should be able to review the change within the next 48 hours – more likely this evening.

 

Cheers,

Geoff

 

From: Colin Robbins ***@***.***> 
Sent: 04 January 2023 16:02
To: GeoffAtHome/lightwave ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GeoffAtHome/lightwave] Remove need for Proxy (Issue #9)

 

Hi Geoff,

I've made a PR to remove the need for a proxy in HA.
I have the permissions I need accept the PR, and create the PyPI.
Just want to check you are OK with the update before I do.

Cheerrs.

**Comment by ColinRobbins** [comment]
A code review would be great.
I’ll hold off until the weekend.

The (minimal) corresponding change for HA is in my staging area.
https://github.com/ColinRobbins/Home-Assistant-Core/tree/lightwave
I can’t PR that, until I’ve made this library available.

I’ve been running with it in my live systems for a week, and all seems fine.
